# Generated by Django 5.0.14 on 2025-10-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('products', 'Товары'), ('orders', 'Заказы'), ('stock', 'Остатки'), ('categories', 'Категории')], max_length=20, verbose_name='Тип синхронизации')),
                ('status', models.CharField(choices=[('started', 'Начата'), ('success', 'Успешно'), ('error', 'Ошибка')], default='started', max_length=20, verbose_name='Статус')),
                ('items_processed', models.IntegerField(default=0, verbose_name='Обработано элементов')),
                ('items_created', models.IntegerField(default=0, verbose_name='Создано элементов')),
                ('items_updated', models.IntegerField(default=0, verbose_name='Обновлено элементов')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_id', models.CharField(max_length=255, unique=True, verbose_name='ID в МойСклад')),
                ('number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('processing', 'В обработке'), ('shipped', 'Отгружен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента')),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон клиента')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email клиента')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Полные данные из API')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['moysklad_id'], name='integration_moyskla_eac96c_idx'), models.Index(fields=['number'], name='integration_number_c1d673_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_id', models.CharField(max_length=255, unique=True, verbose_name='ID в МойСклад')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Себестоимость')),
                ('stock', models.IntegerField(default=0, verbose_name='Остаток')),
                ('reserve', models.IntegerField(default=0, verbose_name='Резерв')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('external_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний код')),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, verbose_name='Штрихкод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Полные данные из API')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['moysklad_id'], name='integration_moyskla_893e39_idx'), models.Index(fields=['article'], name='integration_article_d48cf7_idx'), models.Index(fields=['code'], name='integration_code_70e39a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_id', models.CharField(max_length=255, unique=True, verbose_name='ID в МойСклад')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='integration.productcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
    ]
