# Generated by Django 5.2.10 on 2026-02-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladproduct',
            name='site_category',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Категория сайт'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='site_subcategory',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Подкатегория сайт'),
        ),
    ]
