# Generated by Django 5.2.10 on 2026-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_moyskladproduct_site_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='reserve',
        ),
        migrations.RemoveField(
            model_name='moyskladproduct',
            name='stock',
        ),
        migrations.AlterField(
            model_name='synclog',
            name='sync_type',
            field=models.CharField(choices=[('products', 'Товары'), ('orders', 'Заказы'), ('categories', 'Категории'), ('brands', 'Бренды')], max_length=20, verbose_name='Тип синхронизации'),
        ),
    ]
