# Generated by Django 5.2.1 on 2026-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_remove_stock_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladproduct',
            name='site_category_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID категории сайт'),
        ),
        migrations.AddField(
            model_name='moyskladproduct',
            name='site_subcategory_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID подкатегории сайт'),
        ),
    ]
