# Generated by Django 5.2.10 on 2026-01-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(db_index=True, max_length=50, verbose_name='Парсер')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('error', 'Ошибка')], default='running', max_length=20, verbose_name='Статус')),
                ('total_items', models.IntegerField(default=0, verbose_name='Всего URL')),
                ('items_created', models.IntegerField(default=0, verbose_name='Создано')),
                ('items_updated', models.IntegerField(default=0, verbose_name='Обновлено')),
                ('errors_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'Запуск парсера',
                'verbose_name_plural': 'Запуски парсеров',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(db_index=True, max_length=50, verbose_name='Парсер')),
                ('source_url', models.URLField(max_length=500, unique=True, verbose_name='URL источника')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='Артикул производителя')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('short_description', models.CharField(blank=True, max_length=1000, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('brand', models.CharField(db_index=True, max_length=100, verbose_name='Бренд')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Характеристики')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='Документы (PDF)')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Видео')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Связан с товаром')),
                ('parsed_at', models.DateTimeField(auto_now=True, verbose_name='Дата парсинга')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_data', to='products.product', verbose_name='Товар PIM')),
            ],
            options={
                'verbose_name': 'Спарсенный товар',
                'verbose_name_plural': 'Спарсенные товары',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('local_file', models.ImageField(blank=True, upload_to='scraped/', verbose_name='Локальный файл')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Скачано')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='scraping.scrapedproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='scrapedproduct',
            index=models.Index(fields=['parser_name', 'sku'], name='scraping_sc_parser__23f0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedproduct',
            index=models.Index(fields=['brand', 'sku'], name='scraping_sc_brand_c70b90_idx'),
        ),
    ]
