# Generated by Django 5.2.10 on 2026-01-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_attributedefinition_code'),
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(db_index=True, max_length=50, verbose_name='Парсер')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL категории')),
                ('source_category_name', models.CharField(blank=True, help_text='Как категория называется на сайте-источнике', max_length=255, verbose_name='Название категории на сайте')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('items_found', models.IntegerField(default=0, verbose_name='Найдено товаров')),
                ('items_parsed', models.IntegerField(default=0, verbose_name='Спарсено товаров')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parser_tasks', to='references.brand', verbose_name='Бренд')),
                ('target_category', models.ForeignKey(help_text='Товары получат обязательные атрибуты этой категории', on_delete=django.db.models.deletion.PROTECT, related_name='parser_tasks', to='references.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Задание на парсинг',
                'verbose_name_plural': 'Задания на парсинг',
                'db_table': 'scraping_parser_task',
                'ordering': ['-created_at'],
                'unique_together': {('parser_name', 'source_url')},
            },
        ),
    ]
