# Generated by Django 5.2.10 on 2026-01-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_productcard_slug'),
        ('scraping', '0002_parsertask'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scrapedproduct',
            name='scraping_sc_parser__23f0f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='scrapedproduct',
            name='scraping_sc_brand_c70b90_idx',
        ),
        migrations.RemoveField(
            model_name='scrapedproduct',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='scrapedproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scrapedproduct',
            name='is_matched',
        ),
        migrations.RemoveField(
            model_name='scrapedproduct',
            name='parser_name',
        ),
        migrations.RemoveField(
            model_name='scrapedproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='scrapedproduct',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AddField(
            model_name='scrapedproduct',
            name='parser_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='scraping.parsertask', verbose_name='Задание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapedproduct',
            name='processed_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_scraped', to='cards.productcard', verbose_name='Созданная карточка'),
        ),
        migrations.AlterField(
            model_name='scrapedproduct',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Формат: {"_raw": {...}, "length": {"value": 2000, "unit": "mm"}, ...}', verbose_name='Характеристики'),
        ),
        migrations.AddIndex(
            model_name='scrapedproduct',
            index=models.Index(fields=['parser_task', 'sku'], name='scraping_sc_parser__3845f8_idx'),
        ),
    ]
