# Generated by Django 5.2.10 on 2026-01-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_remove_scrapedproduct_scraping_sc_parser__23f0f2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsertask',
            name='parsing_depth',
            field=models.CharField(choices=[('catalog', 'Только каталог (быстро)'), ('detail', 'Страницы товаров (полные данные)')], default='catalog', help_text='catalog — данные из карточек каталога; detail — заходим на каждую страницу товара', max_length=20, verbose_name='Глубина парсинга'),
        ),
    ]
