# Generated by Django 5.2.10 on 2026-01-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_parsertask_parsing_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsertask',
            name='parsing_depth',
        ),
    ]
