# Generated by Django 5.2.10 on 2026-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_remove_parsertask_parsing_depth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedproduct',
            name='processed_card',
        ),
    ]
