# Generated by Django 5.0.14 on 2026-01-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('value_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'products_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'products_productcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'products_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'products_productattributevalue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products_productimage',
                'managed': False,
            },
        ),
    ]
