# Generated by Django 5.0.14 on 2025-11-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_id', models.CharField(max_length=255, unique=True, verbose_name='ID МойСклад')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('external_code', models.CharField(blank=True, max_length=255, verbose_name='Внешний код')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная')),
                ('is_wholesale', models.BooleanField(default=False, verbose_name='Оптовая')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип цены',
                'verbose_name_plural': 'Типы цен',
                'db_table': 'pim_price_type',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product', verbose_name='Товар')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.pricetype', verbose_name='Тип цены')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'db_table': 'pim_price',
                'unique_together': {('product', 'price_type')},
            },
        ),
    ]
