# Generated by Django 5.2.10 on 2026-01-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('moysklad', 'МойСклад'), ('parser', 'Парсер')], max_length=50, verbose_name='Источник')),
                ('source_name', models.CharField(help_text='Как атрибут называется в источнике (Power, Мощн., и т.д.)', max_length=255, verbose_name='Название в источнике')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='references.attributedefinition', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name': 'Маппинг атрибута',
                'verbose_name_plural': 'Маппинг атрибутов',
                'db_table': 'mapping_attribute',
                'ordering': ['attribute__name', 'source'],
                'unique_together': {('source', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='BrandMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('moysklad', 'МойСклад'), ('parser', 'Парсер')], max_length=50, verbose_name='Источник')),
                ('source_name', models.CharField(help_text='Как бренд называется в МойСклад или на сайте', max_length=255, verbose_name='Название в источнике')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='references.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Маппинг бренда',
                'verbose_name_plural': 'Маппинг брендов',
                'db_table': 'mapping_brand',
                'ordering': ['brand__name', 'source'],
                'unique_together': {('source', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('moysklad', 'МойСклад'), ('parser', 'Парсер')], max_length=50, verbose_name='Источник')),
                ('source_name', models.CharField(help_text='Путь или название категории в источнике', max_length=500, verbose_name='Название в источнике')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='references.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Маппинг категории',
                'verbose_name_plural': 'Маппинг категорий',
                'db_table': 'mapping_category',
                'ordering': ['category__title', 'source'],
                'unique_together': {('source', 'source_name')},
            },
        ),
    ]
