# Generated by Django 5.2.10 on 2026-01-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
        ('references', '0003_remove_brand_aliases_alter_brand_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandmapping',
            options={'ordering': ['source_name'], 'verbose_name': 'Маппинг бренда', 'verbose_name_plural': 'Маппинг брендов'},
        ),
        migrations.AlterField(
            model_name='brandmapping',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='references.brand', verbose_name='Бренд'),
        ),
    ]
