# Generated by Django 5.0.14 on 2025-11-30 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('value_type', models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('decimal', 'Десятичное'), ('boolean', 'Да/Нет')], default='string', max_length=20, verbose_name='Тип значения')),
                ('filter_type', models.CharField(choices=[('none', 'Не фильтруется'), ('exact', 'Точное совпадение'), ('range', 'Диапазон'), ('checkbox', 'Множественный выбор')], default='checkbox', max_length=20, verbose_name='Тип фильтра')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Фильтруемый')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.attributedefinition')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Атрибут категории',
                'verbose_name_plural': 'Атрибуты категорий',
                'ordering': ['sort_order'],
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', through='catalog.CategoryAttribute', to='catalog.attributedefinition', verbose_name='Атрибуты'),
        ),
    ]
