# Generated by Django 5.0.14 on 2025-11-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, verbose_name='SKU')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Короткое описание')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
                'db_table': 'pim_product_card',
                'ordering': ['-is_default', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.productcard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'pim_product_card_image',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_values', to='catalog.attributedefinition', verbose_name='Атрибут')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cards.productcard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Атрибут карточки',
                'verbose_name_plural': 'Атрибуты карточек',
                'db_table': 'pim_product_card_attribute',
                'ordering': ['sort_order'],
                'unique_together': {('card', 'attribute')},
            },
        ),
    ]
