# Generated by Django 5.2.10 on 2026-01-08 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(blank=True, max_length=1000, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.CharField(choices=[('manual', 'Ручной ввод'), ('parsed', 'Из парсинга')], default='manual', max_length=20, verbose_name='Источник')),
                ('scraped_source_url', models.URLField(blank=True, help_text='Откуда были взяты данные (для справки)', verbose_name='URL источника парсинга')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Карточка контента',
                'verbose_name_plural': 'Карточки контента',
                'db_table': 'pim_product_card',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.productcard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'pim_product_card_image',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductCardAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=6, help_text='Для числовых атрибутов — значение в базовых единицах', max_digits=20, null=True, verbose_name='Нормализованное значение')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_values', to='references.attributedefinition', verbose_name='Атрибут')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='cards.productcard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Атрибут карточки',
                'verbose_name_plural': 'Атрибуты карточки',
                'db_table': 'pim_product_card_attribute',
                'ordering': ['sort_order'],
                'unique_together': {('card', 'attribute')},
            },
        ),
    ]
