# Generated by Django 5.2.10 on 2026-01-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='slug',
        ),
    ]
