# Generated by Django 5.2 on 2026-02-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_productcard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='source',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('parsed', 'Из парсинга'), ('moysklad', 'Из МойСклад')], default='manual', max_length=20, verbose_name='Источник'),
        ),
    ]
