# Generated by Django 5.2.10 on 2026-03-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_productcard_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcardimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='cards/', verbose_name='Изображение'),
        ),
    ]
