# Generated by Django 5.2.10 on 2026-01-08 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('value_type', models.CharField(choices=[('string', 'Строка'), ('integer', 'Целое число'), ('decimal', 'Десятичное'), ('boolean', 'Да/Нет')], default='string', max_length=20, verbose_name='Тип значения')),
                ('filter_type', models.CharField(choices=[('none', 'Не фильтруется'), ('exact', 'Точное совпадение'), ('range', 'Диапазон'), ('checkbox', 'Множественный выбор')], default='checkbox', max_length=20, verbose_name='Тип фильтра')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('symbol', models.CharField(max_length=20, verbose_name='Символ')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Варианты написания: ["kg", "КГ", "килограмм"]', verbose_name='Синонимы')),
                ('multiplier', models.DecimalField(decimal_places=10, default=1, help_text='Коэффициент для перевода в базовую единицу (кг→г = 1000)', max_digits=20, verbose_name='Множитель')),
                ('is_base', models.BooleanField(default=False, help_text='Единица в которой хранятся значения', verbose_name='Базовая единица')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['group', '-is_base', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('base_unit_symbol', models.CharField(help_text='Все значения хранятся в этих единицах (г, мм, мл, Вт)', max_length=20, verbose_name='Символ базовой единицы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Группа единиц',
                'verbose_name_plural': 'Группы единиц',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='references.category', verbose_name='Родительская')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательный')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='Фильтруемый')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Сортировка')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.attributedefinition')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.category')),
            ],
            options={
                'verbose_name': 'Атрибут категории',
                'verbose_name_plural': 'Атрибуты категорий',
                'ordering': ['sort_order'],
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='category',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='categories', through='references.CategoryAttribute', to='references.attributedefinition', verbose_name='Атрибуты'),
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='Используется если при парсинге единица не указана', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_attributes', to='references.unit', verbose_name='Единица по умолчанию'),
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='references.unitgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='unit_group',
            field=models.ForeignKey(blank=True, help_text='Для числовых характеристик с единицами измерения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='references.unitgroup', verbose_name='Группа единиц'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('group', 'symbol')},
        ),
    ]
