# Generated by Django 5.2.10 on 2026-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='aliases',
            field=models.JSONField(blank=True, default=list, help_text='Варианты написания из источников данных', verbose_name='Синонимы'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='ref_brand',
        ),
    ]
