# Generated by Django 5.2.10 on 2026-01-08 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_brand_aliases_alter_brand_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='aliases',
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
    ]
