# Generated by Django 5.2.10 on 2026-01-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_remove_brand_aliases_alter_brand_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='code',
            field=models.CharField(blank=True, help_text='Стандартный код: length, height, thickness, weight, material', max_length=50, null=True, unique=True, verbose_name='Код'),
        ),
    ]
