# Generated by Django 5.2.1 on 2026-03-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_expand_slug_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
