# Generated by Django 5.2.1 on 2026-04-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_expand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='moysklad_id',
            field=models.CharField(blank=True, help_text='UUID значения справочника customentity в МойСклад', max_length=255, null=True, unique=True, verbose_name='ID в МойСклад'),
        ),
    ]
