# Generated by Django 5.0.14 on 2025-11-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moysklad_id', models.CharField(max_length=255, unique=True, verbose_name='ID МойСклад')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='SKU (код)')),
                ('article', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Артикул')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Штрихкод')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Объём (м³)')),
                ('is_kaspi', models.BooleanField(default=False, verbose_name='Товар Kaspi')),
                ('is_satu', models.BooleanField(default=False, verbose_name='Товар Satu')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акция')),
                ('moysklad_path', models.CharField(blank=True, max_length=500, verbose_name='Путь в МойСклад')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(auto_now=True, verbose_name='Последняя синхронизация')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
