# Generated by Django 5.2.1 on 2026-03-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Страна производитель'),
        ),
    ]
